export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';
export const LOAD_COURSE_FAILURE = 'LOAD_COURSE_FAILURE';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const LOAD_AUTHOR_FAILURE = 'LOAD_AUTHOR_FAILURE';
